// What we know about stock ZMK: the keycode/parameter macros from its
// dt-bindings headers (vendored in zmk-defines.json) and its built-in
// behaviors (from app/dts/behaviors/*.dtsi).

import ZmkDefinesJson from "./zmk-defines.json";
import { MacroTable, preprocess } from "./preprocessor";

// Generated by scripts/generate-zmk-defines.ts.
interface ZmkDefinesData {
  source: string;
  keycodes: [string, number][];
  deprecatedKeycodes: [string, number][];
  // header file -> [name, cells]
  constants: Record<string, [string, number[]][]>;
  functionMacros: string[];
}

const ZmkDefines = ZmkDefinesJson as unknown as ZmkDefinesData;

export type ParamKind = "hid" | "layer" | "value";

export interface BuiltinBehavior {
  // devicetree label, as written after `&` in a keymap
  label: string;
  // display-name(s) the firmware reports over the Studio RPC. Behaviors
  // without a display-name report their node name instead.
  displayNames: string[];
  cells: number;
  // What each cell means, used when the device gives us no metadata.
  params: ParamKind[];
  // Header whose constants name this behavior's parameters, and which of
  // its names apply (pointing.h is shared by three behaviors).
  constantsHeader?: string;
  constantsMatch?: RegExp;
}

export const BUILTIN_BEHAVIORS: BuiltinBehavior[] = [
  { label: "kp", displayNames: ["Key Press", "key_press"], cells: 1, params: ["hid"] },
  { label: "mo", displayNames: ["Momentary Layer", "momentary_layer"], cells: 1, params: ["layer"] },
  { label: "lt", displayNames: ["Layer-Tap", "layer_tap"], cells: 2, params: ["layer", "hid"] },
  { label: "mt", displayNames: ["Mod-Tap", "mod_tap"], cells: 2, params: ["hid", "hid"] },
  { label: "tog", displayNames: ["Toggle Layer", "toggle_layer"], cells: 1, params: ["layer"] },
  { label: "to", displayNames: ["To Layer", "to_layer"], cells: 1, params: ["layer"] },
  { label: "sl", displayNames: ["Sticky Layer", "sticky_layer"], cells: 1, params: ["layer"] },
  { label: "sk", displayNames: ["Sticky Key", "sticky_key"], cells: 1, params: ["hid"] },
  { label: "kt", displayNames: ["Key Toggle", "key_toggle"], cells: 1, params: ["hid"] },
  { label: "trans", displayNames: ["Transparent", "transparent"], cells: 0, params: [] },
  { label: "none", displayNames: ["None", "none"], cells: 0, params: [] },
  { label: "gresc", displayNames: ["Grave/Escape", "grave_escape"], cells: 0, params: [] },
  { label: "caps_word", displayNames: ["Caps Word", "caps_word"], cells: 0, params: [] },
  { label: "key_repeat", displayNames: ["Key Repeat", "key_repeat"], cells: 0, params: [] },
  { label: "sys_reset", displayNames: ["Reset", "sysreset"], cells: 0, params: [] },
  { label: "bootloader", displayNames: ["Bootloader", "bootload"], cells: 0, params: [] },
  { label: "soft_off", displayNames: ["Soft Off", "z_so_off"], cells: 0, params: [] },
  { label: "studio_unlock", displayNames: ["Studio Unlock", "studio_unlock"], cells: 0, params: [] },
  { label: "bt", displayNames: ["Bluetooth", "bluetooth"], cells: 2, params: ["value", "value"], constantsHeader: "bt.h" },
  { label: "out", displayNames: ["Output Selection", "outputs"], cells: 1, params: ["value"], constantsHeader: "outputs.h" },
  { label: "rgb_ug", displayNames: ["Underglow", "rgb_ug", "RGB Underglow"], cells: 2, params: ["value", "value"], constantsHeader: "rgb.h" },
  { label: "bl", displayNames: ["Backlight", "bcklight"], cells: 2, params: ["value", "value"], constantsHeader: "backlight.h" },
  { label: "ext_power", displayNames: ["External Power", "extpower"], cells: 1, params: ["value"], constantsHeader: "ext_power.h" },
  { label: "mkp", displayNames: ["Mouse Key Press", "mouse_key_press"], cells: 1, params: ["value"], constantsHeader: "pointing.h", constantsMatch: /^(MB\d|[LRM]CLK)$/ },
  { label: "mmv", displayNames: ["Mouse Move", "mouse_move"], cells: 1, params: ["value"], constantsHeader: "pointing.h", constantsMatch: /^MOVE_/ },
  { label: "msc", displayNames: ["Mouse Scroll", "mouse_scroll"], cells: 1, params: ["value"], constantsHeader: "pointing.h", constantsMatch: /^SCRL_/ },
];

const normalize = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");

export function builtinByLabel(label: string): BuiltinBehavior | undefined {
  return BUILTIN_BEHAVIORS.find((b) => b.label === label);
}

export function builtinByDisplayName(name: string): BuiltinBehavior | undefined {
  const n = normalize(name);
  return BUILTIN_BEHAVIORS.find((b) => b.displayNames.some((d) => normalize(d) === n));
}

// Turn an arbitrary display name into something usable as a devicetree label.
export function toLabel(name: string): string {
  const label = name
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return /^[a-z_]/.test(label) ? label : `b_${label}`;
}

export function labelsMatch(label: string, displayName: string): boolean {
  return normalize(label) === normalize(displayName);
}

// ---------------------------------------------------------------------------
// Macros available to every keymap without an #include, as if the standard
// ZMK headers had been included.

let builtinMacros: MacroTable | undefined;

export function zmkMacros(): MacroTable {
  if (!builtinMacros) {
    const lines = [...ZmkDefines.functionMacros];
    for (const [name, value] of [...ZmkDefines.keycodes, ...ZmkDefines.deprecatedKeycodes]) {
      lines.push(`#define ${name} ${value}`);
    }
    for (const entries of Object.values(ZmkDefines.constants)) {
      for (const [name, cells] of entries) {
        lines.push(`#define ${name} ${cells.join(" ")}`);
      }
    }
    builtinMacros = preprocess(lines.join("\n")).macros;
  }
  return builtinMacros;
}

export const KNOWN_INCLUDES = new Set([
  "behaviors.dtsi",
  "dt-bindings/zmk/keys.h",
  "dt-bindings/zmk/bt.h",
  "dt-bindings/zmk/outputs.h",
  "dt-bindings/zmk/rgb.h",
  "dt-bindings/zmk/backlight.h",
  "dt-bindings/zmk/ext_power.h",
  "dt-bindings/zmk/pointing.h",
  "dt-bindings/zmk/mouse.h",
  "dt-bindings/zmk/modifiers.h",
  "dt-bindings/zmk/hid_usage.h",
  "dt-bindings/zmk/hid_usage_pages.h",
  "dt-bindings/zmk/reset.h",
  "dt-bindings/zmk/matrix_transform.h",
  "dt-bindings/zmk/matrix-transform.h",
  "dt-bindings/zmk/input_transform.h",
  "behaviors/mouse_keys.dtsi",
  "input/processors.dtsi",
]);

// ---------------------------------------------------------------------------
// Value -> name, for export.

const MODIFIER_FUNCTIONS = ["LC", "LS", "LA", "LG", "RC", "RS", "RA", "RG"];

let keycodeNames: Map<number, string> | undefined;

function preferredKeycodeNames(): Map<number, string> {
  if (!keycodeNames) {
    // Several names share a value (N1/NUMBER_1, RET/ENTER/RETURN...). Use the
    // shortest non-deprecated one; ties go to the one ZMK defines first.
    keycodeNames = new Map();
    for (const [name, value] of ZmkDefines.keycodes) {
      const existing = keycodeNames.get(value);
      if (!existing || name.length < existing.length) {
        keycodeNames.set(value, name);
      }
    }
  }
  return keycodeNames;
}

// Format a HID usage (possibly carrying implicit modifiers in the top byte) as
// a ZMK keycode expression such as `A`, `EXCL` or `LC(LS(T))`.
export function keycodeName(value: number): string | undefined {
  const names = preferredKeycodeNames();
  const direct = names.get(value >>> 0);
  if (direct) return direct;

  const mods = (value >>> 24) & 0xff;
  const base = names.get(value & 0x00ffffff);
  if (!base || !mods) return undefined;

  let expr = base;
  for (let bit = 7; bit >= 0; bit--) {
    if (mods & (1 << bit)) expr = `${MODIFIER_FUNCTIONS[bit]}(${expr})`;
  }
  return expr;
}

export function constantsFor(behavior: BuiltinBehavior): [string, number[]][] {
  if (!behavior.constantsHeader) return [];
  return (ZmkDefines.constants[behavior.constantsHeader] || []).filter(
    ([name]) =>
      !name.endsWith("_CMD") &&
      !name.startsWith("ZMK_") &&
      (!behavior.constantsMatch || behavior.constantsMatch.test(name))
  );
}

export const zmkDefinesSource = ZmkDefines.source;
